FROM egaillera/meteo-aviso-base-rpi:latest

MAINTAINER E. Garcia "egaillera@gmail.com"

# Install project software
COPY . /home/meteo/meteo-aviso-be
WORKDIR /home/meteo/meteo-aviso-be
RUN chown -R meteo:meteo /home/meteo/meteo-aviso-be 

# Create logs directory
USER meteo
RUN mkdir -p /home/meteo/meteo-aviso-be/app/logs

# Start server
RUN chmod +x start_rpi.sh
WORKDIR /home/meteo/meteo-aviso-be/app
CMD ["../start_rpi.sh"] 
