FROM python:3.6

MAINTAINER E. Garcia "egaillera@gmail.com"

#RUN groupadd -r meteo && useradd -r -g meteo meteo

# Install needed packages
RUN apt-get -y update
RUN apt-get -y install vim
RUN apt-get -y install sudo 

# Create meteo user with sudo permissions and no password
RUN adduser --disabled-password --gecos '' meteo
RUN adduser meteo sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Install dependencies 
COPY ./requirements.txt /tmp/requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install -r /tmp/requirements.txt

