FROM python:3.5

MAINTAINER E. Garcia "egaillera@gmail.com"

RUN groupadd -r meteo && useradd -r -g meteo meteo

# Install vim
RUN apt-get -y update
RUN apt-get -y install vim

# Install dependencies 
COPY ./requirements.txt /tmp/requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install -r /tmp/requirements.txt

